name: Test feature PR

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Test feature PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x
      - run: cd app
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
