name: Release PR into main

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test release PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x

      - run: cd app && npm ci
      - run: cd app && npm run build --if-present
      - run: cd app && npm test