name: Release branch push

on:
  push:
    branches:
      - release/*

jobs:
  test:
    name: Test release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x
      - run: cd app && npm ci
      - run: cd app && npm run build --if-present
      - run: cd app && npm test

      - name: Get app version
        run: node -p -e '`APP_VERSION=${require("./app/package.json").version}`' >> $GITHUB_ENV

      - name: Git tag with release version
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ env.APP_VERSION }}-staging
          git_commit_sha: ${{ github.sha }}
